### PR TITLE
Spanish Translation updated

### PR DESCRIPTION
**Pull request by carmenfdezb**

### CODE REVIEW

**Comment by mkiol** [comment]
Super thanks!

**Comment by carlosgonz0** [comment]
hi Carmen F.B
can you update the spanish file please.
thanks of advance.

**Comment by carmenfdezb** [comment]
Hi GNUuser! Sorry, I didn't noticed for the new texts to translate. I'll do today or tomorrow

**Comment by mkiol** [comment]
@carmenfdezb Sorry. It is my fault. I didn't send any notice that file is ready for translation.

**Comment by carmenfdezb** [comment]
@mkiol @GNUuser Done!
Thanks to both!

**Pull request merged**
