### PR TITLE
Updated czech translation

### PR DESCRIPTION
**Pull request by RikudouSage**

### CODE REVIEW

**Comment by mkiol** [comment]
@RikudouSage I'm planning to release new version to harbour. I was wondering if it would be possible if you could update your translation.

**Comment by RikudouSage** [comment]
@mkiol sorry, I'm a bit late, I can add it later this week if it's still wanted.

**Comment by mkiol** [comment]
@RikudouSage Yes, definitely it is still wanted! :-)

**Comment by RikudouSage** [comment]
I created a pull request. :)

**Pull request merged**
