### PR TITLE
Update harbour-zimpedia-de.ts

### PR DESCRIPTION
**Pull request by popanz**

### CODE REVIEW

**Comment by mkiol** [comment]
Thank you!

**Comment by mkiol** [comment]
@popanz I'm planning to release new version to harbour. I was wondering if it would be possible if you could update your translation.

**Comment by popanz** [comment]
Done :)

Am 19.06.2017, 09:51 Uhr, schrieb Mkiol <notifications@github.com>:

> @popanz I'm planning to release new version to harbour. I was wondering  
> if it would be possible if you could update your translation.

**Comment by mkiol** [comment]
Sorry, but I had to add new string. Could you please update you translation? I promise it is the last change before release.

**Comment by popanz** [comment]
Updating the translation isn't that much work. So even if you need to add  
further strings, just let me know...

  Am 22.06.2017, 10:50 Uhr, schrieb Mkiol <notifications@github.com>:

> Sorry, but I had to add new string. Could you please update you  
> translation? I promise it is the last change before release.

**Comment by mkiol** [comment]
Thank you!

**Pull request merged**
