### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by carmenfdezb**
I've added translation to Spanish :)
Thank you for developing this app!!

### CODE REVIEW

**Comment by mkiol** [comment]
Cool! Thank you.

**Comment by mkiol** [comment]
I've updated few lines, so I would be very grateful if you could do your translation update, before I release package to Jolla Store . Thanks!

**Comment by carmenfdezb** [comment]
Done!! ;)

**Comment by mkiol** [comment]
Super thanks!

**Pull request merged**
