### PR TITLE
Create harbour-zimpedia-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted.

### CODE REVIEW

**Comment by mkiol** [comment]
Thank you!

**Comment by mkiol** [comment]
I've just updated few literals, so I would be very grateful if you could do your translation update, before I release new package. Updated [harbour-zimpedia-sv.ts](https://raw.githubusercontent.com/mkiol/Zimpedia/master/sailfish/translations/harbour-zimpedia-sv.ts) is waiting for you :-)

**Comment by eson57** [comment]
Done!

**Comment by mkiol** [comment]
Super thanks! New release with Your work is now available on OpenRepos - version 1.0-2.

**Comment by eson57** [comment]
Thanks a lot! Now I just have to reformat my SD card. It's FAT32 so it will not work with my 6,42 GB zim file.  :)

**Comment by mkiol** [comment]
Ha ha.. I've spent half a day figuring out why I am unable to copy my 5GB file to SD card. Solution was ext4 :-)

**Comment by eson57** [comment]
Yes, it took a while for me too. :)
Are you sure ext4 is the best choise? I was thinking about F2FS, but maybe SFOS has no support?

**Comment by mkiol** [comment]
Sadly I known almost nothing about file systems. Ext4 was the first thing that comes to my mind... If you succeeded with F2FS or others please let me know. I'm curious.

**Comment by eson57** [comment]
Well, I tried to format my card with  GParted on my Debian machine and F2SF didn't even come up as an option so in this case, ext4 is the obvious solution too.

**Pull request merged**
